version: "3"
services:
  mariadb:
    image: mariadb:10
    container_name: interactive_mariadb
    networks:
      default:
        ipv4_address: 192.168.3.3
    environment:
      MARIADB_ALLOW_EMPTY_PASSWORD: "true"
      MARIADB_ROOT_PASSWORD: interactive
      MARIADB_DATABASE: interactive
      MARIADB_USER: interactive
      MARIADB_PASSWORD: interactive
    ports:
      - "3307:3306"

  web:
    build: ./.docker
    container_name: interactive_web
    networks:
      default:
        ipv4_address: 192.168.3.2
    volumes:
      - ./:/var/www/html/
      - ./.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "81:80"
    depends_on:
      - mariadb


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
